server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /identity

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: beaver-identity-${ENV:local}

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      url: ${REDIS_URL}

  flyway:
    enabled: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

jwt:
  secret: ${JWT_SECRET}
  accessTokenValidity: ${JWT_ACCESS_VALIDITY}
  refreshTokenValidity: ${JWT_REFRESH_VALIDITY}
  authDisabled: false

gateway:
  secret: ${GATEWAY_SECRET}

logging:
  level:
    com.beaver: INFO
    org.springframework.security: WARN