spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: user-service-${ENV}

  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  data:
    redis:
      url: ${REDIS_URL}

  flyway:
    enabled: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true