server:
  port: 8080

beaver:
  dev:
    mock-context:
      enabled: true

logging:
  level:
    com.beaver: DEBUG
    org.springframework.security: DEBUG
    org.springframework.boot.autoconfigure.condition: DEBUG
